services:
  - type: web
    name: podpis-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PODPIS_GIST_ID
        value: 87249d52afaaf99fc4e3660672c726fc
      - key: PODPIS_GIST_TOKEN
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
